# Site settings
title: Josip's Blog
header-img: img/home-bg.jpg
email: josipvukoja99@gmail.com
copyright_name: josipvukoja99@gmail.com
description: "I just started this blog, expect more posts in the future"
baseurl: ""
url: "http://stenbln.github.io"
#twitter_username: SBootstrap
github_username:  stenbln
#facebook_username:  StartBootstrap
email_username:  josipvukoja99@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]

gems:
  - jekyll-sitemap